language: node_js
node_js:
  -11.6.0
cache: yarn

install:
  - yarn install

scripts:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages